### ISSUE TITLE
can not change parameters in running phase

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#208]
**there is a firmware ticket about this**
keep this ticket here as placeholder to make sure it gets resolved plz

it is possible to get into a state where you can not change the parameters of a running phase (i.e., the ad-hoc changes for running phases no longer works).

recreate by creating a process, running it, and adding phases (try both splitting the current running phase and adding phases after the current running phase)

**Comment by vdiezel** [comment]
This might be caused by this:
https://trello.com/c/RdOwHrMM/20-phase-transition-published-on-d-hoc-changes-that-do-not-require-a-phase-transition 

That is a firmware issue: After changing something that doesn't require a phase transition, the device still does a phase transition into the same phase and publishes the transition on `{env}/phases/{deviceId}´. With means we have then two phase entries in the progrssion array with the same array in a row - the UI now thinks the currently running phase has already been finished and prevents modifiying it
