### ISSUE TITLE
bug with proceeding to next phase ends a process

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#209]
when an ad-hoc change is made to a currently running phase
then committed
then a phase is added off the end
then a manual transition to next phase is triggered
the process ends instead of going to the next phase

(is this how to create #207?

**Comment by vdiezel** [comment]
This sounds like a firmware issue to me. Check what is being published when you commit the changes by subscribing to `{env}/commands/{deviceId}` in AWS IoT Core. The process can only be finished by the device or when we explicitly fire the `stop` command. 

Do you commit the added phase before you trigger the manual transition to the next phase? It's not explictly listed, while the first commit is listed, that's why I'm asking ;)
