### ISSUE TITLE
Bug when changing processes after ad-hoc change prematurely ends the process

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#248]
Run a process with two phases
the first phase needs to be time based
ad-hoc the first process to be manual transition
submit ad-hoc request
(now you have a greyed out view for buttons?)
attempt to manually transition to next phase
process ends prematurely, skipping final process

**Comment by vdiezel** [comment]
This was a firmware bug and should have been fixed. I guess it popped up again because you were working on a device that didn't have the newest firmware. I think that we need a way to keep track which bugs were fixed on which device firmware because otherwise we are going to be unsure about whether a bug shows up again because it wasn't fixed properly or because the firmware is not updated yet!

I think the professional solution would be to have a table with devices and their firmware version and every firmware version needs to indicate what has been changed, e.g. bufixes, feature implementation...
