### ISSUE TITLE
FU Bug - Processes not displaying once started

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#260]
FU Bug:

Beim Starten dieser Prozesse gelange ich in ein Fenster, was vollkommen weiß ist. Der Reaktor läuft zwar an, aber man kann ihn nicht steuern/sieht keine Daten. Man muss in diesem Fall den Reaktor komplett ausschalten.

believe it is one of these processes:

* 191028_Adjusted PID Heater/Casing/Plate #4 - Mon Oct 28 2019 13:32:41
* 191028_Equilibration - Mon Oct 28 2019 17:44:40

![image](https://user-images.githubusercontent.com/17087405/69346173-a444d180-0c72-11ea-8305-0625e6016777.png)

[move this to in progress and close it once finished plz](https://trello.com/c/G2y9TjMG/37-ui-blank-when-starting-a-process)

I suggest trying to clone the processes, then starting them, or something to try to recreate behavior. We can also look at the lambda error logs, as the timestamps are provided

EDIT: Check process data in the data base to not malformed somehow (id, progression)

**Comment by vdiezel** [comment]
I have checked the processes provided here and I could not find any anomalies there. It could be the same issue Jared encountered. AWS lambda logs are not realy helpful here as it was probably not a backend function that caused the white screen showing up on Marcus' screens ( our backend calls are wrapped in try blocks) but rather 1.) a general frontend code bug or 2.) the data that was delivered by the backend OR by the device (firmware issue then!) turned out to be malformed.

I changed remove this ticket from development as we cannot reproduce this bug easily. We need some reporting mechanism in place when a the application crashes to a white screen, so we see the stack trace!
