### ISSUE TITLE
SPIKE: FU Bug - downloading stream data not working

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#261]
"Ich kann aktuell die Daten eines Controllers während eines Prozesses nicht herunterladen, ist das richtig?"

Marcus references these processes when submitting the bug:

* 191028_Adjusted PID Heater/Casing/Plate #4 - Mon Oct 28 2019 13:32:41
* 191028_Equilibration - Mon Oct 28 2019 17:44:40

[please move this to in progress once this ticket gets picked up](https://trello.com/c/V7griQap/38-check-if-downloading-works-for-all-streams)

this is a SPIKE.
please identify the issue and provide (create) a detailed ticket for someone to pick up as the actual work later

**Comment by vdiezel** [comment]
This issue was caused my two problems:
1. Our download bucket for the producvtion environment was not references properly in the production built: New ticket here: https://github.com/ospin-web-dev/hambda/issues/152
2. Time out issues in the data base. Time out issues will be investigated during the sprint https://github.com/orgs/ospin-web-dev/projects/14
