### ISSUE TITLE
Fix Enable Phase Editing in current running process

### ISSUE THREAD

**Issue by O-Susanoo** [ospin-web-dev/REACTor#328]
It seem to me that somehow we cache the state of editing of a device and only when a user refresh a page we bring the new state and thus allowing us to edit the device parameters

![image](https://user-images.githubusercontent.com/57438770/69536760-e9247d00-0f7e-11ea-91c8-babaeb1cfc2b.png)

**Comment by vdiezel** [comment]
Bug is due to multiple subscriptions and can be reproduced like this: 
Go to device -> dashboard -> refresh -> got to devices in the sidebar -> go to the device again and start a process, result: 
![bug_1](https://user-images.githubusercontent.com/37934155/69707802-b2737180-10fa-11ea-960c-d7bffbe0ffae.png)

Because in the databse we store only one phase entry the bug is gone after refreshing

**Comment by O-Susanoo** [comment]
Glad you solved it

**Comment by vdiezel** [comment]
This was caused because we always created new subscrition in the callLoadDevices() thunk
