### ISSUE TITLE
The UI shows the bioreactor is offline and there is a runnig process

### ISSUE THREAD

**Issue by aahmed2021** [ospin-web-dev/REACTor#362]
All information you provide is _extremely_ helpful to us! Thank you for taking the time.

**Describe the bug**
as you see in the Picture 1 the UI Shows us the bioreactor is offline, but a process is still running.
we are tracking the bioreactor and the Picture 2 Shows, that bioreator send data.
Picture 3 shows the running process.

**To Reproduce**
1. Go to devices, the New York is shown as offline, if you click on it, you see the running process
2. go to the link : https://eu-central-1.console.aws.amazon.com/iot
3. insert : prod/ping/5602794b-6eeb-449b-9f6e-868a66fd1547: this shows that bioreactor is online

**Expected behavior**
I expect that the bioreactor is online in the UI 

**Screenshots**

![image](https://user-images.githubusercontent.com/56728314/70236239-d838f000-1764-11ea-8ad9-a060e0d3c364.png)
![image](https://user-images.githubusercontent.com/56728314/70236298-f43c9180-1764-11ea-91c0-ca156fc80ca3.png)
![image](https://user-images.githubusercontent.com/56728314/70236311-fef72680-1764-11ea-8b84-fe51c867b25d.png)

**Environment**
 - [ ] Development (https://dev.ospin-app.com)
 - [ x ] Production (https://ospin-app.com)

**DeviceID / ProcessID (if applies)**
https://ospin-app.com/device/5602794b-6eeb-449b-9f6e-868a66fd1547/process/93a2f80e-d9f5-4689-a603-5bd3b4ebb243

**Additional context**

**Comment by O-Susanoo** [comment]
we think that the issue can come from an undefined state mainly , if the device publish an unrecognizable state change (like null) this one is kept on the database , so if the device start with such state it may lead to this kind of behavior , the solution is to force state check in hambda so that we are only storing valid states 

an issue have been opened here ospin-web-dev/hambda#169
