### ISSUE TITLE
Edit calibration modal text/behavior/bugs to reduce ambiguity 

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#436]
There was some user confusion surrounding what was going on here:
- [x] change button text
- [x] edit modal text
- [x] edit 'Two-Point-Calibration' Start/End fields to display the **y values** selected (instead of the times/x values, which are currently displayed case) 
- [x] clear 'Offset' value field back to blank when 'Reset Calibration' is clicked && successful
- [x] fix visual issue with calibration modal spacing
- [x] fix state bug with selected calibration type
- [x] clear notifications on error

**edit button text:**
'Cancel' ->'Close'
'Confirm' -> 'Apply'
![image](https://user-images.githubusercontent.com/17087405/71822675-bac5b180-3095-11ea-92de-2f9426f465aa.png)

**edit modal text:**
 - remove the light green smaller text
 - change bolded text to read: 'Calibration deleted successfully'
![image](https://user-images.githubusercontent.com/17087405/71822982-8ef6fb80-3096-11ea-9290-ec2e801b747a.png)

**edit 'Two-Point-Calibration' Start/End fields to display the y values selected (instead of the times/x values, which are currently displayed case)** 
![image](https://user-images.githubusercontent.com/17087405/71824056-f150fb80-3098-11ea-9921-7db988ca0c4e.png)

**visual issue (happens when text wraps):**
![image](https://user-images.githubusercontent.com/17087405/71823662-26108300-3098-11ea-8bf2-41b19aef6bcc.png)

**fix state bug with selected calibration type**
to reproduce: open the calibration modal. change to any calibration option that is not the default of 'Offset'. Close the calibration modal (maybe after doing some range selection, I don't know). Re-open the calibration modal. The current calibration option displayed in the dropdown is 'Offset', even though it is showing the previously selected calibration option last time it was opened. Instead, the calibration modal should EITHER: default to offset OR reload the last selected calibration option. Do whichever is lest area/cleaner in the code base for now as we don't have data on the desired behavior.

**the green text should have disappeared:**
![image](https://user-images.githubusercontent.com/17087405/71825957-26f7e380-309d-11ea-8167-b6c0f08a0913.png)

**Comment by vdiezel** [comment]
regarding point 3: `edit 'Two-Point-Calibration' Start/End fields to display the y values selected (instead of the times/x values, which are currently displayed case)'`

We do want the time stamps, but we should just format them like they are displayed on the graphs instead of seconds.

regarding point 4: `clear 'Offset' value field back to blank when 'Reset Calibration' is clicked && successful`

The Reset Calibration deletes the existing calibration, it does not reset the current input fields. I changed the name of the button to `Delete Calibration` instead of `Reset Calibration`
