### ISSUE TITLE
Investigate possible big bug

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#468]
- given a paused process
- user makes an ad-hoc change to the current phase
- they accept modal, a new phase is created, they get a notification that process has transitioned to the next phase

**does the process remain paused, or does that trigger the next phase to actually start? (the ui still shows paused)**

If this is a bug, please write up a ticket and assign to the current sprint. Close this either way once investigated!

**Comment by vdiezel** [comment]
You were right. While the device should transition into the newly created phase when the current phase has been modified and the changes confirmed, the device should remain in a paused state. It looks like it remains paused, because it does not publish a new state and remains 'paused', but from the values the upstreams are sending I can see that the e.g. pump starts turning again (or at least sending it RPM value; if it really turns I can't tell) once the phase transition happened, which it shouldn't in the paused device state. 

I suspect this is a firmware  issue. I will write up a Trello ticket.

**Comment by vdiezel** [comment]
https://trello.com/c/bv3aGqLS/42-ad-hoc-issue-for-applied-changes-in-paused-device-state
