### ISSUE TITLE
Permissioning Issue re: users up-permissioning other users

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#559]
Spike - not ticket to complete work

When going through the UI with Lina and Jordi, I believe the following occurred:

With Lina as an **operator** on a process
When adding someone else to the process through the access interface
She was able to give them a permission above herself

This needs some investigation, because this could be a problem also in devices

- [ ] Investigate what our **server side** permissioning is re: changing peoples access for both devices and processes. No user should be able to grant anyone else access **above** what they have on a given resource. 

- [ ] Make a ticket describing how to tighten up any found permissioning loopholes on the device/process **server side**

- [ ] Investigate how we can communicate this in a user friendly way on the front end. Users should not be able to select a group which is above their own level on a device (see below). If doable, perhaps provide a tooltip over the dropdown options that says "cant add them as x because you are y" or something? that might be a pain though - so consider a good user friendly solution!

**Comment by vdiezel** [comment]
I checked it, and only somebody who has the 'MANAGE_ACCESS' bit set can add people to the process. Currently thats only process owners or admins on the process. Operatos can't add anybody in the fist place, so Lina was the process owner and therefore she can add a user in any role to it. 

Also if we would introduce a new group A that has the 'MANAGE_ACCESS' rights but less rights than an admin, it would difficult for us to say what can be considered as `up permissioning` because there is no real hierarchy for groups. So in this case somebody from group A could add somebody as an admin to the process, which would grant the new user more access than the granting user.

Thats why the manage access bit has to be set with care. If you compare it with AWS: If you give a user full access to just AWS IAM he could simply create a user that has full access to every AWS service.
