### ISSUE TITLE
Ad-Hoc phases

### ISSUE THREAD

**Issue by aahmed2021** [ospin-web-dev/REACTor#719]
All information you provide is helpful to us! Thank you for taking the time.

**Describe the bug**
if i have a running process and i want to add a new phases, when i apply the changes, then i see this notification "This process is outdated. Another user may have edited it. Refresh". i can no longer change parameters in this phase after this, only if I update the website.

**To Reproduce**
1. Go to celltainer device'
2. Click on 'the running process'
3. Scroll down to 'add a new phase'
4. apply the changes
5. See error

https://ospin-app.com/device/9ef4f0b3-977b-4d36-9760-bba0b789bb0c/process/9c654d69-2d26-4123-8924-7fec05337219

**Expected behavior**
i expect,I can change the parameters arbitrarily,

**Screenshots**
![image](https://user-images.githubusercontent.com/56728314/80470188-f1278500-8941-11ea-844a-0bf336b8ff67.png)

![image](https://user-images.githubusercontent.com/56728314/80470221-fb498380-8941-11ea-8258-0a74016d85e9.png)

**Environment**
 - [ ] Development (https://dev.ospin-app.com)
 - [ ] Staging (https://staging.ospin-app.com)
 - [ x] Production (https://ospin-app.com)
> Note: staging and production use the same database

**Additional context**

**Comment by vdiezel** [comment]
This is probably a firmware bug, see here: https://trello.com/c/Zn1R1E60/47-old-familiar-bug-showing-up-for-adhoc-changes

It keeps popping up now and then. The issue is this: 

The device publishes a phase transition into the phase it is already in when it receives adhoc changes. This confuses the WebApp because the phase it receives is not the next phase that is expected. Because of that it assumes somebody else modifed the process and blocks all adhoc changes!

**Comment by DanielSeehausen** [comment]
thanks @vdiezel ill follow up with this
